on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/build.yml'
      - '*.txt'

jobs:
  cef-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: factory
          script-name: test_pymupdf.py
          report: compilation-report.xml
          mode: app
          nofollow-import-to: |
            pymupdf.mupdf
            
      - name: Test
        run: build/test_pymupdf.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }} ${{ runner.os }}
          path: |
            test.png
            build/test_pymupdf.exe
            compilation-report.xml
