on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/build.yml'
      - '*.txt'

jobs:
  cef-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements*.txt
          
      - name: Set up system dependencies
        shell: bash
        run: |
          echo "Installing dependencies for ${{ matrix.os }}"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            choco install visualstudio2022buildtools --params "--add Microsoft.VisualStudio.Workload.VCTools";
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo none
            #sudo apt update && sudo apt install -y build-essential;
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo none
          fi


      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: factory
          script-name: test_pymupdf.py
          report: compilation-report.xml
          mode: app
          
      - name: Test
        run: build/test_pymupdf.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }} ${{ runner.os }}
          path: |
            test.png
            build/test_pymupdf.exe
            compilation-report.xml
